name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCe4nB_SMne5-xWYFwsm3L4w
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_SUMMIT }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_SUMMIT }}
        uses: Ilshidur/action-discord@master
        with:
          args: "\"`Migraine World Summit - YouTube`\"\n\"**${{ on.youtube.outputs.title }}**\"\n\"${{ on.youtube.outputs.link }}\""
