name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UC_DxwP72GOs-7-uFsiZnU2g
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_AGAIN }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_AGAIN }}
        uses: EBfVince/action-discord@master
        with:
          args: "`Migraine Again - YouTube`\n**${{on.youtube.outputs.title}}**\n${{on.youtube.outputs.link}}"
